name: "Snyk dependency test and monitoring action" 

on:
  push:
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYKTOKEN }}

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to check for Node vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      with:
        args: --all-projects --org=developer-program --exclude=JavaWebAuthnLib
        command: test

    - name: Run Snyk to check for Java vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true
      with:
        args: --org=developer-program backend/lambda-functions/JavaWebAuthnLib
        command: test

  snyk-monitor:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@master

# exclude JavaWebAuthn since it's Maven and exclude clients because the web client is too large to monitor 
# without prune-repeated-subdependencies which will limit vulnerable paths reported, but will not affect 
# reported vulnerabilities

    - name: Run Snyk to monitor for Node vulnerabilities
      uses: snyk/actions/node@master
      with:
        args: --all-projects --org=developer-program --exclude=JavaWebAuthnLib,clients
        command: monitor

# subdependencies pruned to avoid error with large manifests during monitor
    - name: Run Snyk to monitor for client vulnerbailites
      uses: snyk/actions/node@master
      with:
        args: --all-projects --org=developer-program --prune-repeated-subdependencies clients 
        command: monitor

    - name: Run Snyk to monitor for Java vulnerabilities
      uses: snyk/actions/maven@master
      with:
        args: --org=developer-program backend/lambda-functions/JavaWebAuthnLib
        command: monitor
